version: 2

jobs:
  setup:
    working_directory: /go/src/github.com/gaia-pipeline/gaia
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: make get
  test_and_coverage:
    working_directory: /go/src/github.com/gaia-pipeline/gaia
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            set -e
            echo "" > coverage.txt

            for d in $(go list ./... | grep -v vendor | grep -v /testacc); do
              go test -v -race -coverprofile=profile.out -covermode=atomic $d
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
            done
      - run:
          name: Upload test report to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Build binary without frontend
          command: |
            make compile_backend
            ./gaia-linux-amd64 --version
  acceptance_tests:
    working_directory: /go/src/github.com/gaia-pipeline/gaia
    docker:
        - image: gaiapipeline/circleci:0.0.1
          environment:
            GO111MODULE: "ON"
    steps:
      - checkout
      - run:
          name: Run acceptance tests
          command: |
            set -e
            make test-acc
  compile:
    working_directory: /go/src/github.com/gaia-pipeline/gaia
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    steps:
      - checkout
      - run:
          name: Install nvm, node, and npm
          command: |
            wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
            echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
            touch $HOME/.nvmrc
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - run:
          name: Compile frontend and final binary
          command: |
            cd frontend
            nvm install v10.5.0
            npm cache clean --force
            cd ..
            make release
      - store_artifacts:
          path: gaia-linux-amd64

workflows:
  version: 2
  test_and_compile:
    jobs:
      - setup
      - test_and_coverage:
        requires:
          - setup
      - acceptance_tests:
        requires:
          - setup
      - compile:
        requires:
          - setup
